spring:
  application:
    name: sports-data-etl-pipeline
        
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

# Logging Configuration
logging:
  level:
    com.sportsdata.etl: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    
  file:
    name: logs/etl-pipeline.log

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# ETL Pipeline Configuration
etl:
  pipeline:
    batch-size: 1000
    retry-attempts: 3
    timeout-seconds: 300
    
  data-sources:
    teams-csv: "src/main/resources/sample-data/teams.csv"
    players-json: "src/main/resources/sample-data/players.json"
    games-xml: "src/main/resources/sample-data/games.xml"
    
  # S3 Configuration
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:sports-data-etl-bucket}
    region: ${AWS_REGION:us-east-1}
    prefix: ${S3_KEY_PREFIX:sports-data}
    
  quality:
    minimum-score: 0.7
    fail-on-poor-quality: false
    
  monitoring:
    metrics-enabled: true
    detailed-logging: true

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

---
# Production Profile
spring:
  config:
    activate:
      on-profile: production
      
etl:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:sports-data-etl-prod}
    region: ${AWS_REGION:us-east-1}
    prefix: ${S3_KEY_PREFIX:sports-data-prod}
    
logging:
  level:
    com.sportsdata.etl: INFO
    org.springframework: WARN
    
---
# Test Profile
spring:
  config:
    activate:
      on-profile: test
      
etl:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:sports-data-etl-test}
    region: ${AWS_REGION:us-east-1}
    prefix: ${S3_KEY_PREFIX:sports-data-test}
      
logging:
  level:
    com.sportsdata.etl: DEBUG
    org.springframework: INFO 